# https://cirrus-ci.com/github/burghardt/clamfs
task:
  name: FreeBSD build
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-0
      # 11.3 image causes "Agent is not responding!" error
      image_family: freebsd-11-3-snap
      image_family: freebsd-11-2
      image_family: freebsd-10-4
  env:
    CIRRUS_CLONE_DEPTH: 10
  pkginstall_script:
    - pkg install -y devel/autoconf devel/automake devel/pkgconf
    - pkg install -y sysutils/fusefs-libs3 devel/poco devel/boost-libs devel/rlog
  configure_script:
    - sed -i bak -e 's|-Werror ||g' configure.ac
    - sh bootstrap
    - ./configure || { tail -n 300 config.log; false; }
  compile_script:
    - make
  install_script:
    - make install
