image: debian:jessie

script:
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y libfuse-dev libcommoncpp2-dev librlog-dev libpoco-dev libboost-dev
    - sh autogen.sh
    - sh configure
    - make
