language: c

os: linux
dist: trusty
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libfuse-dev libcommoncpp2-dev librlog-dev libpoco-dev

script:
    - sh autogen.sh
    - sh configure
    - make

after_success:
    - bash <(curl -s https://codecov.io/bash)

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dE9gRVq7edfDolq82cStD2N4dT3oS0l45lW+bcn0IcF3mJGX1ZgBfwIozeGE42A6xmMWGF4RIgUnp9jvTBCLrZFk+KnfyjD5p3HJG9Yy6isjN5+Cmq05ulsv3sgEUKkZQA+7vD4A+6h1ZKwb8cA23xS5TwmncU8MDg3zwAwCbaqqb4s0+F1YVT1tVA5rrrfEJL6K+Vlypm5BcdUfe9RY3yKnV5EVJblOHZ9Zxb+b85/0X7VQXsGqed+Wis5fBkaArOXabh46J6F0C4qNlTTbmMr+svgffjeWKCRRUESJ2mqPcuN/v81X79xba+BTrZe/n/FKPPoYEhJeKHHx+CqK8GfrZixzt8306AheMKTOVDl9cyV8sJe3Ey31r03GP+OcLcs7OlFMnB3XugBYs988ClNDruQKUvRQHEbHR30pG1ED5lo1EwOh/IrF8hbpzKAfa6q2BVR3MONfAfmudOq3dhi4PllRG6VMxiAxcRwWHtaOOvTPCx4q3J/KldYYqyZrWJUApnjtSlEfGXI2pW/p9IFKEbCs5+dLzoqdJYV+LCIub1sVTemGbh3dbr7mf/gTF/2dJOwxiPSVvKZneTJK16QKWyvLm4e4ZdSvK+CFwCrMQRubD9xSDlOjNuyVQkpto+Tyb9IadWvfMa0eYfW6S97duDL2rxlGbRqORmkGm3U="

addons:
  coverity_scan:
    project:
      name: "burghardt/clamfs"
      description: "Build submitted via Travis CI"
    notification_email: krzysztof@burghardt.pl
    build_command_prepend: "sh autogen.sh ; sh configure ; make clean"
    build_command:   "make -j 4"
    branch_pattern: master
