name: doxygen workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  test:
    name: doxygen
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install \
               build-essential \
               automake \
               doxygen \
               libfuse-dev \
               librlog-dev \
               libpoco-dev \
               libboost-dev
      - name: bootstrap
        run: sh bootstrap
      - name: configure
        run: sh configure
      - name: clean
        run: make clean
      - name: doxygen
        run: |
          cd doc
          doxygen
