name: quick workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install \
               build-essential \
               automake \
               libfuse-dev \
               libcommoncpp2-dev \
               librlog-dev \
               libpoco-dev \
               libboost-dev
      - name: bootstrap
        run: sh bootstrap
      - name: configure
        run: sh configure
      - name: make
        run: make
      - name: prepare
        run: |
          set -x
          sudo apt-get install -y clamav-daemon
          sudo systemctl stop clamav-freshclam
          sudo freshclam
          sudo systemctl restart clamav-freshclam
          sudo systemctl restart clamav-daemon
          # wait for clamd to initialize
          sleep 1m
      - name: mount
        run: |
          sudo mkdir -p /clamfs/tmp
          sudo ./src/clamfs ./doc/clamfs.xml
      - name: empty
        run: |
          cd /clamfs/tmp
          touch empty.file
          cat empty.file
      - name: string
        run: |
          cd /clamfs/tmp
          echo 'Hello World!' > string.txt
          cat string.txt
      - name: eicar
        run: |
          cd /clamfs/tmp
          echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > eicar.com
          hexdump -C eicar.com && exit 1
          sudo grep 'Eicar-Test-Signature' /var/log/syslog
